web:
  image: .
  ports:
   - "8080:8080"
  links:
   - mysql:db

dbdata:
  image: mysql:latest
  volumes:
   - /var/lib/mysql
   
mysql:
  image: mysql:latest
  ports:
   - "3306:3306"
  volumes_from:
   - dbdata
  environment:
    MYSQL_ROOT_PASSWORD: root
