version: '3.0'  
services:
  web:
    build: .
    container_name: web
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    links:
      - mysql:db
  mysql:  
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    container_name: db
volumes:
  dbdata:
networks:
  towar-net: